### ISSUE TITLE
coordination with gnuplot project

### ISSUE THREAD

**Issue by bruceravel** [emacsorphanage/gnuplot#22]
It seems that the gnuplot project points its users at a fairly old version of gnuplot-mode.

See http://gnuplot.info/ReleaseNotes_5_0.html (and search down the page for "emacs") and https://github.com/rudi/gnuplot-el

I am about to open an issue there suggesting that gnuplot point here instead.

**Comment by conao3** [comment]
[rudi/gnuplot-el](https://github.com/rudi/gnuplot-el) seems now shutdown. Please use this project for gnuplot integration.
