### ISSUE TITLE
gnuplot session hangs emacs with inline data blocks (gnuplot version 5.0)

### ISSUE THREAD

**Issue by jxy** [emacsorphanage/gnuplot#23]
Using gnuplot version 5.0, after typing the beginning of an inline data block, the gnuplot session hangs.

Try typing the following line in the session buffer:

``` gnuplot
$Mydata << EOD
1 2
EOD
```

You won't be able to start typing the second line.  Emacs hangs at

```
accept-process-output(#<process gnuplot>)
comint-send-input()
call-interactively(comint-send-input nil nil)
command-execute(comint-send-input)
```

**Comment by conao3** [comment]
This is not possible because the `*gnuplot*` buffer is not an actual prompt.
Write it to another buffer and send it `C-c C-c`.
