### ISSUE TITLE
Circular dependency between gnuplot websites ;)

### ISSUE THREAD

**Issue by rudi** [emacsorphanage/gnuplot#24]
Hi,

The github site starts with 

> This directory contains files for running Gnuplot from within emacs. This package was assembled by Bruce Ravel bruceravel1@gmail.com. See the homepage at http://xafs.org/BruceRavel/GnuplotMode

whereas that URL starts with

> See https://github.com/bruceravel/gnuplot-mode

Infinite redirects! ;)

Also, while I'm here: I'm dealing with some fallout of my own upload of gnuplot.el to github over at https://sourceforge.net/p/gnuplot/bugs/1544/ -- just to make it clear, I wasn't involved in the gnuplot 5.0 release notes pointing to my decommissioned github project..

**Comment by conao3** [comment]
Circular dependency is resolved now :)
