### ISSUE TITLE
gnuplot-mode: Comment/uncomment region

### ISSUE THREAD

**Issue by NikoSauer** [emacsorphanage/gnuplot#30]
Attached is elisp code for commenting/uncommenting a region. It works for Xemacs. Also attached is a diff to show how I modified gnuplot.el

**Comment by NikoSauer** [comment]
Links- Code Comment.el; gnuplot.el.patch

**Comment by NikoSauer** [comment]
GIST LINKS:
For diff-file:
https://gist.github.com/NikoSauer/4c724b911bee12e978a753a309fcba86 

For elisp code:
https://gist.github.com/NikoSauer/464e9f4e9898e1823671bc57da5a8771

**Comment by conao3** [comment]
Please use active region, and type `M-;`.
