### ISSUE TITLE
font-lock mode comment coloring is wrong when line continues

### ISSUE THREAD

**Issue by KNAnagnostop** [emacsorphanage/gnuplot#32]
When a command that is continued to a next line is commented, the following lines are colored the opposite way: Comments as code and code as comments. See attached screenshot.
gnuplot-mode 0.7 (gnuplot 3.7)
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17
Ubuntu 16.04.1 LTS
kernel
![gnuplot-mode](https://cloud.githubusercontent.com/assets/21079718/17734075/b531e8b6-6482-11e6-9c8f-2d6614a320a1.png)
 4.4.0-34-generic  x86_64 GNU/Linux

**Comment by conao3** [comment]
Currently, solved this issue.
![Screenshot_2020-03-21_13-49-59](https://user-images.githubusercontent.com/4703128/77219721-9d27c480-6b7b-11ea-8ebb-a5d4062f1e38.png)
