### ISSUE TITLE
Gnuplot version (5.0) not detected

### ISSUE THREAD

**Issue by tartifola** [emacsorphanage/gnuplot#34]
Hi,
after a fresh install of Linux Mint 18.1 Serena I have a problem with gnuplot-mode detecting the installed version of Gnuplot and reverting to 3.7.  In the message buffer of Emacs I get

gnuplot-mode 0.7-beta -- determining gnuplot version ......
Warning: could not determine gnuplot version, guessing 3.7
gnuplot-mode 0.7-beta (gnuplot 3.7) -- report bugs with "C-c C-u"

Here some details on the version of the programs installed:

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
gnuplot 5.0 patchlevel 3
gnuplot-mode 0.7-beta

Do you have any guess on why? Workaround?

Let me take this opportunity to thank all of you for your work really helpful in may daily working life.

Best,

**Comment by hanyudeye** [comment]
gnuplot-program "/usr/bin/gnuplot"
gnuplot-program-version "5.2"
gnuplot-program-major-version 5
gnuplot-program-minor-version 2
 

i set it by hand

**Comment by mtreca** [comment]
I decided to fix this issue by ... removing gnuplot version numbers altogether (see the message of commit df47e87 for an explanation). You should be able to use the package regardless of your gnuplot version (provided it is >= to 5.0), and drop the manual version config from your `init.el` !
