### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by conao3** [emacsorphanage/gnuplot#40]
There is anyone who has push permissions for this project thinking to maintain this repository?

I think the world still needs this project, and the `ob-gnuplot` at [org-contrib](https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-gnuplot.html) depends on it.
If you have any problem managing this, you can add some collaborators or transfer repository to [emacs-orphanage](https://github.com/emacsorphanage) and have the community maintain the package.
Friendly ping.

**Comment by bruceravel** [comment]
Hi Naoya,

I would be happy to transfer the repo to the orphanage.  There isn't really any documentation for how to do this transfer.  Let me know what works best for you and I will do so.

Cheers,
Bruce

**Comment by conao3** [comment]
Thanks for the quick reply!
I am a member of the organization, but I do not have the authority to accept transport from you. It can only @tarsius.

---
To @tarsius
@bruceravel seems to want to transfer this repository to Emacsorphanage. Could you tell him how?

**Comment by tarsius** [comment]
@bruceravel I have invited you to become a "member" of the Emacsorphanage. Once you have accepted you should be able to transfer this repository there.

After that I can give you more permissions for this repository or revoke member ship altogether, depending on how involved you want to stay.

**Comment by conao3** [comment]
Thanks @tarsius!

**Comment by conao3** [comment]
ping? How this operation state?

**Comment by bruceravel** [comment]
Hi @conao3, 
Sorry for being so slow.  It was quite a week last week at work.

I just accepted @tarsius invitation, so we can proceed from there.
B

**Comment by tarsius** [comment]
Next step is that you transfer the repository. Click on `Settings` in the menu above and then `Transfer` near the bottom of the settings page. You should have the necessry permissions to transfer to the `emacsorphanage` organisation.

**Comment by bruceravel** [comment]
@tarsius @conao3 Done!

**Comment by conao3** [comment]
Good! Thanks!

**Comment by tarsius** [comment]
Okay then.

@bruceravel Do you want to stay involved? I.e. should I

(a) make you a maintainer of this repository, or
(b) remove you from the organization altogether?

**Comment by tarsius** [comment]
> (b) remove you from the organization altogether?

I went with that approach.

**Comment by conao3** [comment]
@tarsius, please add commit authority for me?

**Comment by tarsius** [comment]
> please add commit authority for me?

I have just done that.

At the same time I have to ask you to do major refactorings on feature branches and to not merge immediately merge those into master. I wasn't planning to comment on that, but I think I have to mention that IMO your work on `solarized-theme` has been merged *much* too early. If you make such huge changes, then please ask me to review before merging anything.

(I do not want to comment on the fight that broke out due to the premature merge over at solarized, except to say that both sides have to take some of the blame and that such fights happen even to nice people and the important thing is to move on.)

**Comment by tarsius** [comment]
Carrying over from the previous location, @joddie still had access. I have revoked that access because he wasn't active on Github at all for three years and hasn't participated in this conversation. Of course we would be excited to welcome him back.

**Comment by conao3** [comment]
Yes, that conflict is no-needed and waste many people's time. That's my fault.

Anyway, as you can see from other my work in emacsorphanage, I never push directly to the master.
Only @tarsius has the right to push to this repository other than me, so I will always ask you to review it, but thank you.
