### ISSUE TITLE
Latest master causes issues

### ISSUE THREAD

**Issue by vxid** [emacsorphanage/gnuplot#46]
Mulitple users report being unable to properly use gnuplot in the latest release.

See [here](https://www.mail-archive.com/emacs-orgmode@gnu.org/msg127211.html) for an email thread about this.

I get the following message when starting `gnuplot-mode` in my Emacs (tested with `emacs -Q` and simply opening and org-mode gnuplot block):

```
gnuplot-mode 0.7-beta -- determining gnuplot version ......
Warning: could not determine gnuplot version, guessing 3.7
Initialization fails with: "Invalid menu item in easymenu"
```

Gnuplot used to work perfectly for me a few weeks ago (after a fresh pull). Looking at the commit history, maybe one of the reformatting commits is messing something up?

**Comment by conao3** [comment]
Thanks to informing me org mailing list relating this package!
It seems to be mixed in the [untabifed commit](https://github.com/emacsorphanage/gnuplot/commit/8f2ddd0df772368add7dda5b1c6ac60ac48f976d#diff-8df7f8cc7a2ea43b8406f1256ffef4c9R1002). I really don't know why it was mixed in, but I'm sorry for the inconvenience.

To continue using `gnuplot` on `org`, we need to maintain `org`, but we also need to maintain this package.
I want to invite you as a collaborator.
@tarsius, please invite @vxid to `emacsorphanage` and add him to `gnuplot` team. I don't have the authority to do that.

**Comment by vxid** [comment]
@conao3 Thanks for the quick fix and the invitation!

**Comment by tgrigera** [comment]
Thanks for the fix, I thought the issue was with org and reported in that list. Thanks to @vxid for reporting to the appropriate place.

**Comment by tarsius** [comment]
@vxid So you want to become a maintainer of this package?

**Comment by vxid** [comment]
@tarsius I would like to help maintain the package (this is what I understood from @conao3's message) but not being the sole maintainer (I have only a little experience with gnuplot).

**Comment by vxid** [comment]
#47 fixes the issue.
