### ISSUE TITLE
Drop XEmacs support

### ISSUE THREAD

**Issue by mtreca** [emacsorphanage/gnuplot#50]
I don't know what you think about this @conao3 but dropping support for XEmacs (and older version of Emacs, but I will open a separate issue for this) could simplify the code quite a bit by removing a lot of workarounds and hack.

More specifically, the comment string of `gnuplot-toolbar-use-toolbar` states that the gnuplot tool bar does not work on GNU Emacs. Can anyone confirm this? If this is the case, should we aim at porting the toolbar features to GNU Emacs or just drop them altogether?

**Comment by vxid** [comment]
Similarly, looking at the codebase, I think this package should drop support for gnuplot < 4.0, which was released in 2004. It would simplify a lot of `gnuplot-three-eight-p` assertions.

**Comment by vxid** [comment]
I did not know that @bruceravel was still active on this project, so paging him for is opinion, especially regarding the toolbar!

**Comment by conao3** [comment]
We can drop support for XEmacs, I think too. It also makes sense to support Emacs-24.4 or later, considering that the user can download it from MELPA using `package.el`.

But before we do any large refactoring, we should create tests and set up CIs.

**Comment by vxid** [comment]
@conao3 I agree. There are a number of compilation warnings we should take care of too.

**Comment by mtreca** [comment]
closed with #59
