### ISSUE TITLE
plot with different types

### ISSUE THREAD

**Issue by mfrasca** [emacsorphanage/gnuplot#56]
(not sure whether this is the right place to ask, but let's see)

I'm plotting two series of data that's daily measurements, and a running average, from emacs.
I wish to have the daily measurements as points, the running averages as lines.

is there a way to do that?  my guess was:

```
#+PLOT: ind:1 deps:(3 6 4 7) with:(points lines points lines)
```

but the list is not iterated and instead I get a `Wrong type argument: stringp, (points lines points lines)` error.

**Comment by mtreca** [comment]
Hello and sorry for the (very late) reply.

My gnuplot skill level is not great, so I can't really answer your question here.

I am going to close this issue since it is definitely a question related to gnuplot and not gnuplot.el, but if any gnuplot whizz finds this thread and knows the answer they can feel free to re-open it and answer.

**Comment by mfrasca** [comment]
ooh, so sorry, I had forgotten about having ever opened this issue here, thank you for reviving it.  I have implemented it myself, and it **is** quite definitely a gnuplot.el issue, not gnuplot.

```lisp
(ert-deftest test-org-plot/zip-deps-with ()
  "Test `org-plot/zip-deps-with' specifications."
  ;; no deps, no with. defaults to all except ind, and "lines"
  (should
   (equal (org-plot/zip-deps-with 3 1 nil nil)
	  '((2 . "lines") (3 . "lines"))))
  ;; no deps, single with. defaults to all except ind, and repeated with
  (should
   (equal (org-plot/zip-deps-with 3 1 nil "hist")
	  '((2 . "hist") (3 . "hist"))))
  ;; no deps, explicit with
  (should
   (equal (org-plot/zip-deps-with 3 1 nil '("points" "hist"))
	  '((2 . "points") (3 . "hist"))))
  ;; explicit with, same length as deps
  (should
   (equal (org-plot/zip-deps-with 5 1 '(2 4) '("points" "hist"))
	  '((2 . "points") (4 . "hist"))))
  ;; same as above, but different order
  (should
   (equal (org-plot/zip-deps-with 5 1 '(4 2) '("points" "hist"))
	  '((4 . "points") (2 . "hist"))))
  ;; if with exceeds deps, trailing elements are discarded
  (should
   (equal (org-plot/zip-deps-with 5 1 '(4 2) '("points" "hist" "lines"))
	  '((4 . "points") (2 . "hist"))))
  ;; fills in with "lines"
  (should
   (equal (org-plot/zip-deps-with 5 1 '(4 2 3) '("points"))
	  '((4 . "points") (2 . "lines") (3 . "lines")))))```

**Comment by mtreca** [comment]
I guess that would depend on `ob-gnuplot` then, but I might be wrong.
In any case, you're more than welcome to submit a PR if you can find a solution to your problem that could benefit others!

**Comment by mfrasca** [comment]
possibly we're both wrong.  I dislike `ob-gnuplot` and I insist using `org-plot/gnuplot`, apparently abandonware within org.
