### ISSUE TITLE
pause -1 makes gnuplot hang in emacs

### ISSUE THREAD

**Issue by bruceravel** [emacsorphanage/gnuplot#6]
Jim Mehl says: “I usually put pause -1 lines in my gnuplot scripts. I have to be careful to comment these out if I execute the script within emacs. It just hangs. Is there a way out?”
When run in a terminal the pauses let me review the screen, then proceed (like many gnuplot demo scripts). When I run this script within emacs 23.1.1 with gnuplot-mode (gnuplot 4.5), emacs becomes unresponsive. I cannot switch buffers. I can switch to another window and kill emacs (usually undesirable).

```
plot [-5:5] sin(x)/x
pause -1
plot [-5:5] (sin(x)/x)**2
pause -1
```

**Comment by conao3** [comment]
Now `pause -1` could cancel via `C-c C-c` in `*gnuplot*` buffer.
