### ISSUE TITLE
gnuplot-trim-gnuplot-buffer issue, integer-or-marker-p nil

### ISSUE THREAD

**Issue by avillafiorita** [emacsorphanage/gnuplot#73]
Hi 
thanks for the code, which I use very often, really appreciated!

I run into the error mentioned in the subject line when sending a (any) region to a gnuplot buffer.

The issue seems to be related to the new version of the `gnuplot-trim-gnuplot-buffer` function; this is where, at least, the debugger kicks in. Notice that the gnuplot code is executed ok (and plots generated as they should), but the evaluator triggers the error.

The issue kicks in when using gnuplot in org-mode buffers. In these cases the execution of the first gnuplot block triggers the error and the evaluation of the buffer (and other code blocks) stops.

I seem to get the error systematically. The old version works fine.

**Comment by mtreca** [comment]
Hi and thanks for reporting this issue. I did change this function very recently because it polluted the yank ring. It seems I introduced a bug in doing so. I will look into it right now.

**Comment by mtreca** [comment]
So I did notice that my let binding is missing a pair of parens, which I fixed locally (it did trigger a warning that I did not see when pushing, sorry about that). However, I am not getting the error you have. Could you send a copy of the backtrace and your Emacs version?

**Comment by avillafiorita** [comment]
Hi, 
thanks for the prompt answer; here is what triggers the error on my computer.

/usr/bin/emacs -q 

M-x load-file 
~/.emacs.d/elpa/gnuplot-20210526.1848/gnuplot-autoloads.el

M-x version 
GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-26

Then:

1. Open the attached file [gnuplot.script.txt](https://github.com/emacsorphanage/gnuplot/files/6606445/gnuplot.script.txt), which reads the following data: [data.txt](https://github.com/emacsorphanage/gnuplot/files/6606448/data.txt)
2. Send the buffer to gnuplot

and, if the debugger is active:

Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  gnuplot-trim-gnuplot-buffer()
  run-hooks(gnuplot-after-plot-hook)
  gnuplot-send-string-to-gnuplot("reset \n\nset boxwidth 0.5\nset grid ytics linestyle ..." buffer)
  gnuplot-send-region-to-gnuplot(1 372 buffer)
  gnuplot-send-buffer-to-gnuplot()
  funcall-interactively(gnuplot-send-buffer-to-gnuplot)
  call-interactively(gnuplot-send-buffer-to-gnuplot nil nil)
  command-execute(gnuplot-send-buffer-to-gnuplot)

(I don't know whether there is a way to collect an Emacs Lisp trace to file.)

I hope it helps!

**Comment by mtreca** [comment]
Thanks for the report. I did use the files you provided and GNU Emacs 27.2 with no config file. I am getting the issue regarding a missing set of parens in the let statement of `gnuplot-trim-gnuplot-buffer`, but nothing regarding your particular issue. I just pushed a fix regarding the missing parens. COuld you try to see if using this version works?

**Comment by avillafiorita** [comment]
Hi -
I just tried and indeed it works fine, now.
Thanks for the support!
